version: "3.8"

services:

  mysql-db:
    container_name: mysql-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: go_clean_arch_db
    networks:
      - mysql-network

  my-golang-app:
    container_name: my-golang-app
    image: brayrizqiev/golang-bryan
    ports:
      - 8080:8080
    networks:
      - mysql-network
    environment:
      DB_USERNAME: root
      DB_PASSWORD: secret
      DB_HOST: mysql-db
      DB_NAME: go_clean_arch_db
    restart: always
    depends_on:
      - mysql-db

networks:
  mysql-network:
      name: mysql-network
      driver: bridge
