// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "belajar-go-echo/module/user/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepositoryInterface type
type UserRepository struct {
	mock.Mock
}

// GetAllUser provides a mock function with given fields:
func (_m *UserRepository) GetAllUser() ([]entity.UserDTO, error) {
	ret := _m.Called()

	var r0 []entity.UserDTO
	if rf, ok := ret.Get(0).(func() []entity.UserDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertUser provides a mock function with given fields: userDTO
func (_m *UserRepository) InsertUser(userDTO entity.UserDTO) error {
	ret := _m.Called(userDTO)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.UserDTO) error); ok {
		r0 = rf(userDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
